
package cero;

import org.jdesktop.application.Action;

/**
 * SwingAboutBox represents the graphical window to display certain
 * information about the application.  Such information includes the
 * names of the developers, and the current version and build of Cero.
 *
 * @author Ilya Seletsky - Javadocs
 * @author Matt Carson - Psuedocode, Source Code
 * @version 1.0 - February 27, 2010
 */

public class SwingAboutBox extends javax.swing.JDialog
{

    /**
     * Creates a new dialog box to display information about the game.
     *
     * @param   parent    the main application frame
     */
    public SwingAboutBox(java.awt.Frame parent)
    {
        super(parent);
        initComponents();
        getRootPane().setDefaultButton(closeButton);
        AboutBox ab = new AboutBox();
        //developers.setText("<html>" + ab.getDevelopers());
        developers.setText(ab.getDevelopers());
        version.setText(ab.getVersion());
        build.setText(ab.getBuild());
    }

    /**
     * Closes the dialog box.
     */
    @Action public void closeAboutBox()
    {
        setVisible(false);
        dispose();
    }

    /**
     * Initializes the components of the dialog box.
     * <P>
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     * </P>
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teamLog = new javax.swing.JLabel();
        version = new javax.swing.JLabel();
        build = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        developers = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(cero.CeroApp.class).getContext().getResourceMap(SwingAboutBox.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setModal(true);
        setName("aboutBox"); // NOI18N
        setResizable(false);

        teamLog.setIcon(resourceMap.getIcon("teamLog.icon")); // NOI18N
        teamLog.setText(resourceMap.getString("teamLog.text")); // NOI18N
        teamLog.setName("teamLog"); // NOI18N

        version.setText(resourceMap.getString("version.text")); // NOI18N
        version.setName("version"); // NOI18N

        build.setText(resourceMap.getString("build.text")); // NOI18N
        build.setName("build"); // NOI18N

        closeButton.setText(resourceMap.getString("closeButton.text")); // NOI18N
        closeButton.setName("closeButton"); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        developers.setBackground(resourceMap.getColor("developers.background")); // NOI18N
        developers.setColumns(20);
        developers.setEditable(false);
        developers.setRows(5);
        developers.setName("developers"); // NOI18N
        jScrollPane1.setViewportView(developers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teamLog, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(build, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(version, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(213, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                            .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(version, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(build, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(teamLog, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed
    //changed developers into a JTextArea fixes defect # 264
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel build;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextArea developers;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel teamLog;
    private javax.swing.JLabel version;
    // End of variables declaration//GEN-END:variables
    
}
