/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StatusPanel.java
 *
 * Created on Feb 22, 2010, 3:54:16 PM
 */

package tolecoFunctionalPrototype.GUI;

import java.awt.image.BufferedImage;
import javax.swing.OverlayLayout;
import tolecoFunctionalPrototype.Core.*;

/**
 *
 * @author eaugusti
 */
public class StatusPanel extends javax.swing.JPanel {

    private BattleSummary sum;
    private UnitSelected unit;
    private BackStory bs;
    private TerrainSelected ts;

    /** Creates new form StatusPanel */
    public StatusPanel() {

       initComponents();
       bs = new BackStory();
       unit = new UnitSelected();
       sum = new BattleSummary();
       ts = new TerrainSelected();

       this.setLayout(new OverlayLayout(this));

       add(bs);
       add(unit);
       add(sum);
       add(ts);

       bs.setEnabled(false);
       bs.setVisible(false);

       ts.setEnabled(false);
       ts.setVisible(false);

       sum.setEnabled(false);
       sum.setVisible(false);

       unit.setEnabled(false);
       unit.setVisible(false);
    }

    public void gotoStateUnit(Location loc)
    {
       unit.setLocation(loc);

       bs.setEnabled(false);
       bs.setVisible(false);

       ts.setEnabled(false);
       ts.setVisible(false);
       
       sum.setEnabled(false);
       sum.setVisible(false);

       unit.setEnabled(true);
       unit.setVisible(true);

       validate();
       repaint();
    }

    public void gotoStateBackStory(String back)
    {
       bs.setStory(back);

       bs.setEnabled(true);
       bs.setVisible(true);

       ts.setEnabled(false);
       ts.setVisible(false);

       sum.setEnabled(false);
       sum.setVisible(false);

       unit.setEnabled(false);
       unit.setVisible(false);

       validate();
       repaint();
    }

    public void gotoStateTerrain(Terrain ter)
    {
       ts.setTerrain(ter);

       bs.setEnabled(false);
       bs.setVisible(false);

       ts.setEnabled(true);
       ts.setVisible(true);

       sum.setEnabled(false);
       sum.setVisible(false);

       unit.setEnabled(false);
       unit.setVisible(false);

       validate();
       repaint();
    }

    public void gotoStateBattleSummary(Unit atk, Unit def, String summary)
    {
       sum.setSummary(atk, def, summary);

       bs.setEnabled(false);
       bs.setVisible(false);

       ts.setEnabled(false);
       ts.setVisible(false);

       sum.setEnabled(true);
       sum.setVisible(true);

       unit.setEnabled(false);
       unit.setVisible(false);

       validate();
       repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      setPreferredSize(new java.awt.Dimension(200, 300));

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 200, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 300, Short.MAX_VALUE)
      );
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   // End of variables declaration//GEN-END:variables

}
