/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TerrainSelected.java
 *
 * Created on Feb 19, 2010, 1:16:48 PM
 */

package tolecoFunctionalPrototype.GUI;
import javax.swing.*;
import tolecoFunctionalPrototype.Core.*;

/**
 *
 * @author eralston
 */
public class TerrainSelected extends JPanel{

 


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      terrainName = new javax.swing.JLabel();
      terrainPortrait = new javax.swing.JLabel();
      moveName = new javax.swing.JLabel();
      movePoints = new javax.swing.JLabel();
      defenseName = new javax.swing.JLabel();
      defenseBonus = new javax.swing.JLabel();

      setPreferredSize(new java.awt.Dimension(200, 300));

      terrainName.setText("jLabel1");
      terrainName.setPreferredSize(new java.awt.Dimension(44, 30));

      terrainPortrait.setPreferredSize(new java.awt.Dimension(80, 80));

      moveName.setText("jLabel1");
      moveName.setPreferredSize(new java.awt.Dimension(44, 25));

      movePoints.setText("jLabel1");
      movePoints.setPreferredSize(new java.awt.Dimension(44, 20));

      defenseName.setText("jLabel1");
      defenseName.setPreferredSize(new java.awt.Dimension(44, 25));

      defenseBonus.setText("jLabel1");
      defenseBonus.setPreferredSize(new java.awt.Dimension(44, 25));

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGap(52, 52, 52)
                  .addComponent(terrainPortrait, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(layout.createSequentialGroup()
                  .addContainerGap()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(defenseBonus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                     .addComponent(defenseName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                     .addComponent(movePoints, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                     .addComponent(moveName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                     .addComponent(terrainName, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(terrainName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(terrainPortrait, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(moveName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(movePoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(defenseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(defenseBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(22, Short.MAX_VALUE))
      );
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel defenseBonus;
   private javax.swing.JLabel defenseName;
   private javax.swing.JLabel moveName;
   private javax.swing.JLabel movePoints;
   private javax.swing.JLabel terrainName;
   private javax.swing.JLabel terrainPortrait;
   // End of variables declaration//GEN-END:variables
   /** Creates new form TerrainSelected */
    public TerrainSelected() {
        initComponents();
    }

    public void setTerrain(Terrain ter) {

        terrainName.setText(ter.name);
        terrainName.setHorizontalAlignment(SwingConstants.CENTER);
        terrainPortrait.setIcon(new ImageIcon(ter.artPortrait));
        moveName.setText("Move Cost");
        moveName.setHorizontalAlignment(SwingConstants.CENTER);
        movePoints.setText(""+ter.moveCost);
        movePoints.setHorizontalAlignment(SwingConstants.CENTER);
        defenseName.setText("Defense Bonus");
        defenseName.setHorizontalAlignment(SwingConstants.CENTER);
        defenseBonus.setText("+"+ter.defModifier);
        defenseBonus.setHorizontalAlignment(SwingConstants.CENTER);
    }
}
